# Generated by Django 4.0.6 on 2022-07-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(max_length=1000),
            preserve_default=False,
        ),
    ]
